
CREATE TABLE Users(
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  enabled boolean not null DEFAULT TRUE ,
  PRIMARY KEY (username)
);

CREATE TABLE Profile(
  username VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  VALUE VARCHAR(100) NOT NULL,
  FOREIGN KEY (username) REFERENCES Users(username)
);

CREATE TABLE MessageKeys(
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  VALUE VARCHAR(100) NOT NULL,
  ISWHITE boolean NOT NULL,
  FOREIGN KEY (ID) REFERENCES Message(ID)
  ON DELETE CASCADE
);

CREATE TABLE Coordinates(
  NAME VARCHAR(100) NOT NULL,
  Lat FLOAT( 10, 6 ) NOT NULL ,
  Lon FLOAT( 10, 6 ) NOT NULL ,
  Radius INT NOT NULL,
  FOREIGN KEY (NAME) REFERENCES Location(NAME)
  ON DELETE CASCADE
);

CREATE TABLE Location(
  NAME VARCHAR(100) NOT NULL,
  SSID VARCHAR(100) NULL,
  BLE VARCHAR(100) NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE Message(
  ID VARCHAR(36) NOT NULL,
  LOCATION VARCHAR(100) NOT NULL,
  CONTENT VARCHAR(1000) NOT NULL,
  CREATIONTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STARTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ENDTIME TIMESTAMP NULL,
  PUBLISHER VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (LOCATION) REFERENCES Location(name),
  FOREIGN KEY (PUBLISHER) REFERENCES Users(username)
);

CREATE TABLE ListType(
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE List(
  MSGID VARCHAR(36) NOT NULL,
  TYPE VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NULL,
  VALUE VARCHAR(100) NULL,
  FOREIGN KEY (TYPE) REFERENCES ListType(NAME),
  FOREIGN KEY (NAME) REFERENCES Profile(NAME),
  FOREIGN KEY (VALUE) REFERENCES Profile(VALUE),
  FOREIGN KEY (MSGID) REFERENCES Message(ID),
  PRIMARY KEY (MSGID,TYPE)
);




